### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by remcohaszing**
This module looks interesting. :)

I added some TypeScript type definitions. Feel free to merge if you want, or close if not. Or let me know if you want some type tests added.

### CODE REVIEW

**Comment by fisker** [comment]
I'm not done with the API yet.

**Comment by fisker** [comment]
Thanks for the help. I'm done with the API design now.

Do you think it's possible to generate `.d.ts` from `.js` file? [I did it once](https://github.com/fisker/iterate-directory-up/blob/56556424f7196c74fc59a053e8d718a99a63d5de/package.json#L30).

**Comment by remcohaszing** [comment]
I got quite far, but did not finish this yesterday. However, the latest version introduces dual publishing built from a single source. This makes it impossible to generate correct types from the JavaScript.

I propose to manually write type definitions for the exports, though the current ones are outdated. Then optionally I can type check the JavaScript based on these manually written type definitions and JSDoc type annotations.

**Comment by fisker** [comment]
> This makes it impossible to generate correct types from the JavaScript.

Why? Shouldn't ts able to bundle as both esm and commonjs?

**Comment by remcohaszing** [comment]
In TypeScript, each `.ts` file represents one `.js` file, and one `.d.ts` file. If you dual publish, you want to generate both a CJS and ESM type definitions and JavaScript.

The fact that this isn’t intended usage of TypeScript, doesn’t stop the community from trying. One solution could be to use [`tsup`](https://tsup.egoist.dev/#typescript--javascript) to build the project.

If you have a build process, you might as well use TypeScript instead of types in JSDoc by the way. It allows for more powerful TypeScript features. I’m not trying to convince you though, it’s your choice.

I also realized that there’s not really a point in dual publishing this package. It only targets Node.js. The main part of the package could be CJS only, and the worker could be ESM only. This way the worker can import both CJS and ESM, and the package can be imported from both CJS and ESM. Also dual publishing affects the Synchronizer cache due to the [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard).

**Comment by fisker** [comment]
> I also realized that there’s not really a point in dual publishing this package.

I was assuming that people needs this feature are stuck at the commonjs environment(for example tools for ESLint), so I have to ship the cjs version, otherwise they have to `await import()` this module, but you are right that I don't need bundle `worker.js` to cjs, only `index.cjs` should be used.

**Comment by remcohaszing** [comment]
> I was assuming that people needs this feature are stuck at the commonjs environment(for example tools for ESLint), so I have to ship the cjs version

I get that, and I understand this is a minimal requirement. I also get why you would prefer to use ESM, I personally prefer ESM too. But if you already publish CJS, there’s no point in publishing ESM additionally. If the `index.js` entrypoint is written with CJS, the build step would no longer be necessary.

**Comment by fisker** [comment]
> But if you already publish CJS, there’s no point in publishing ESM additionally.

Yes, and this is why [prettier-synchronized](https://github.com/prettier/prettier-synchronized) is CommonJS only. But feels good to use a native ESM entry. :smile: The file size is slightly smaller.

> If the index.js entrypoint is written with CJS

More prefer to use ESM syntax.

**Comment by remcohaszing** [comment]
> More prefer to use ESM syntax

I absolutely agree, but ESM users can import CJS perfectly fine.

> and better tree-shake support too.

Normally I agree with this being an advantage of ESM. However, this project needs to resolve the worker relative to the source code. It doesn’t support bundling, so tree shaking isn’t relevant.

Also, due to the [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard), there are two synchronizer caches: one for the CJS version, one for the ESM version.

**Comment by fisker** [comment]
> I absolutely agree

So, why this .cjs file makes you unhappy? Because of types? I don't really care... and it's not really a problem at all.


```
    "exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": {
                // Where TypeScript will look.
                "types": "./types/esm/index.d.ts",
                // Where Node.js will look.
                "default": "./esm/index.js"
            },
            // Entry-point for `require("my-package") in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./types/commonjs/index.d.cts",
                // Where Node.js will look.
                "default": "./commonjs/index.cjs"
            },
        }
    },
```

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html

> there are two synchronizer caches: one for the CJS version, one for the ESM version.

Why this matters?

**Comment by remcohaszing** [comment]
> So, why this `.cjs` file makes you unhappy? 

It complicates the build process for no benefit. Note that I’m not saying we shouldn’t use `.cjs`. I’m saying that **if** you provide a CJS version, **then** there are no benefits providing an ESM version.

> Do you think it's possible to generate `.d.ts` from `.js` file?

This is why. Using TypeScript it’s not possible to generate both CJS and ESM type definitions from one source file. If you want this, you need to use another build tool, like `tsup`.

If you want to keep the setup as-is, the only way to add types is to author them by hand.

I want to make sure we’re on the same line on how the types are created, as it affects the build process.

> > there are two synchronizer caches: one for the CJS version, one for the ESM version.
>
> Why this matters?

It’s a really small potential performance hit. An ESM project could use `import 'make-synchronized'` and import 'prettier-synchronized'` for example. This argument is really a minor detail IMO. Let’s not focus on that.

**Comment by fisker** [comment]
> This is why. Using TypeScript it’s not possible to generate both CJS and ESM type definitions from one source file.

I hardly think so. Anyway, you can also send types to https://github.com/DefinitelyTyped/DefinitelyTyped, feel free to do that. I don't use types at all.

**Comment by remcohaszing** [comment]
> Using TypeScript it’s not possible to generate both CJS and ESM type definitions from one source file.

This is really true though. It’s one of the main reasons people use third party tooling for it, of which some do an ok’ish job, whereas others do it plain wrong.

> Anyway, you can also send types to https://github.com/DefinitelyTyped/DefinitelyTyped

That’s another equally valid way to provide types. I’ll do that instead :)

---

I feel like this got a bit lost in conversation, but I think this is a really cool project. Thanks for creating it. :heart:

**Pull request closed without merging**
